### ISSUE TITLE
Tidak ada batas per kalimat pada dataset

### ISSUE THREAD

**Issue by AnakTeka** [ialfina/ner-dataset-modified-dee#1]
Pada Stanford NER CRF baris kosong digunakan sebagai pembatas antar kalimat, sedangkan pada dataset yang ada di git ini tidak terdapat baris kosong yang menjadi pembeda antar kalimat.

**Comment by ialfina** [comment]
Dear Yoga,
Terima kasih atas pemberitahuannya. Anda benar, kami lupa meng-handle batas antar-kalimat. Ada satu langkah preprocessing yang lupa dilakukan.

Mohon maaf, saya baru tahu ada laporan ini. Saya akan coba cari dokumentasi poyek MDEE ini untuk menemukan kalimat asli 20.000 kalimat sebelum ditokenisasi. Jika sudah ketemu, akan segera saya update dataset-nya.
