### ISSUE TITLE
How to separate the sentence?

### ISSUE THREAD

**Issue by allanj** [ialfina/ner-dataset-modified-dee#2]
It seems there is no blank line to separate the sentences.

**Comment by ialfina** [comment]
Dear Allan,
Thank you for your information.
We just found out a bug in the pre-processing step. We used PTBTokenizer of Stanford CoreNLP as the tokenizer. Our mistake is to applied it to all sentences at ones, not one by one. As the result,  we got the resulting dataset with no blank line between sentences.
We will revise the datasets as soon as we managed to find the file of the original 20,000 sentences before the tokenization step applied on.
